CREATE DATABASE PELICULA;

USE PELICULA;

CREATE TABLE PELICULA(
	ID INTEGER AUTO_INCREMENT,
	titulo VARCHAR(50) NOT NULL,
	nota DECIMAL(2,2),
	fecha DATETIME DEFAULT NOW(),
	ID_voto INTEGER,
	PRIMARY KEY(ID),
	CONSTRAINT CHK_NOTA CHECK (nota >= 0 and nota <= 10)
);

CREATE TABLE GASTO(
	gastos DECIMAL(10,2),
	ingresos DECIMAL(10,2),
	ID_gasto INTEGER AUTO_INCREMENT,
	ID_pelicula INTEGER,
	PRIMARY KEY(ID_gasto),
	CONSTRAINT FK_PELICULA_GASTO FOREIGN KEY (ID_pelicula) REFERENCES PELICULA(ID)
);

CREATE TABLE VOTO(
	media_votos DECIMAL(2,2),
	cantidad INTEGER,
	ID_voto INTEGER AUTO_INCREMENT,
	PRIMARY KEY(ID_voto)
);

CREATE TABLE GENERO(
	ID_genero INTEGER AUTO_INCREMENT,
	genero VARCHAR(25),
	PRIMARY KEY(ID_genero)
);

CREATE TABLE GENERO_PELICULA(
	ID_pelicula INTEGER,
	ID_genero INTEGER,
	CONSTRAINT PK_GENERO_PELICULA PRIMARY KEY (ID_pelicula, ID_genero),
	CONSTRAINT FK_PELICULA_GENERO FOREIGN KEY (ID_pelicula) REFERENCES PELICULA(ID),
	CONSTRAINT FK_GENERO FOREIGN KEY (ID_genero) REFERENCES GENERO(ID_genero)
);

CREATE TABLE SECUELAS(
	ID_secuela INTEGER AUTO_INCREMENT,
	ID_pelicula INTEGER,
	PRIMARY KEY(ID_secuela),
	CONSTRAINT FK_PELICULA_SECUELAS FOREIGN KEY (ID_pelicula) REFERENCES PELICULA(ID)
);

ALTER TABLE PELICULA
	ADD CONSTRAINT FK_VOTO FOREIGN KEY (ID_voto) REFERENCES VOTO(ID_voto);